<?php
/**
 * == TracFlo == 
 * Material
 *
 */

if ( ! class_exists('TracFlo_Material') ) {
  class TracFlo_Material {

	var $pluginPath;
	var $pluginUrl;
	
	public function __construct()
	{
		// Set Plugin Path
		$this->pluginPath = dirname(__FILE__);
	
		// Set Plugin URL
		$this->pluginUrl = WP_PLUGIN_URL . '/tracflo';
		
		add_action( 'init', array( $this, 'tf_mt_posttype' ) );					
    	add_action( 'cmb2_init', array( $this, 'tf_mt_metabox' ) );		
	}
	/**
	 * Post Type
	 */	
	public function tf_mt_posttype(){
	
	  $labels = array(
		'name'                  => _x( 'Materials', 'Post Type General Name', 'tf_mt' ),
		'singular_name'         => _x( 'Materials', 'Post Type Singular Name', 'tf_mt' ),
		'menu_name'             => __( 'Materials', 'tf_mt' ),
		'name_admin_bar'        => __( 'Materials', 'tf_mt' ),
		'archives'              => __( 'Material Archives', 'tf_mt' ),
		'parent_item_colon'     => __( 'Parent Material:', 'tf_mt' ),
		'all_items'             => __( 'All Materials', 'tf_mt' ),
		'add_new_item'          => __( 'Add Material', 'tf_mt' ),
		'add_new'               => __( 'Add Material', 'tf_mt' ),
		'new_item'              => __( 'New Material', 'tf_mt' ),
		'edit_item'             => __( 'Edit Material', 'tf_mt' ),
		'update_item'           => __( 'Update Material', 'tf_mt' ),
		'view_item'             => __( 'View Material', 'tf_mt' ),
		'search_items'          => __( 'Search Materials', 'tf_mt' ),
		'not_found'             => __( 'Not found', 'tf_mt' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'tf_mt' ),
		'featured_image'        => __( 'Featured Image', 'tf_mt' ),
		'set_featured_image'    => __( 'Set featured image', 'tf_mt' ),
		'remove_featured_image' => __( 'Remove featured image', 'tf_mt' ),
		'use_featured_image'    => __( 'Use as featured image', 'tf_mt' ),
		'insert_into_item'      => __( 'Insert into item', 'tf_mt' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'tf_mt' ),
		'items_list'            => __( 'Items list', 'tf_mt' ),
		'items_list_navigation' => __( 'Items list navigation', 'tf_mt' ),
		'filter_items_list'     => __( 'Filter items list', 'tf_mt' ),
	);
	$args = array(
		'label'                 => __( 'Materials', 'tf_mt' ),
		'description'           => __( 'Dataset collecting Materials', 'tf_mt' ),
		'labels'                => $labels,
		'supports'              => array( 'comments', 'trackbacks', 'revisions', ),
		'taxonomies'            => array( 'locations' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'tf_material', $args );

	}

	/**
	 * Metabox
	 */	
	public function tf_mt_metabox(){
	
	  // set the prefix (start with an underscore to hide it from the custom fields list
	    $prefix = '_tf_mt_';
	     
	    // Material
	    $cmb = new_cmb2_box( array(
	        'id'            => 'tf_material',
	        'title'         => 'Material Name',
	        'object_types'  => array( 'tf_material' ), // post type
	        'context'       => 'normal', // 'normal', 'advanced' or 'side'
	        'priority'      => 'high', // 'high', 'core', 'default' or 'low'
	        'show_names'    => true, // show field names on the left
	        'cmb_styles'    => false, // false to disable the CMB stylesheet
	        'closed'        => false, // keep the metabox closed by default
	    ) );

	    $cmb->add_field( array(
		    'name'    => 'Material ID',
		    'desc'    => 'Company specific ID, not generated by tracflo',
		    'default' => '',
		    'id'      => 'tf_material_id',
		    'type'    => 'text',
		) );

		$cmb->add_field( array(
		    'name'    => 'Material Name',
		    'desc'    => 'Name associate with Material',
		    'default' => '',
		    'id'      => 'tf_material_name',
		    'type'    => 'text',
		) );

	    $cmb->add_field( array(
		    'name'    => 'Unit Rate',
		    'desc'    => '',
		    'default' => '',
		    'id'      => 'tf_material_straight',
		    'type'    => 'text',
		) );


		$cmb->add_field( array(
		    'name'    => 'Premium Unit Rate',
		    'desc'    => '',
		    'default' => '',
		    'id'      => 'tf_material_premium',
		    'type'    => 'text',
		) );

		// attachments
		$cmb->add_field( array(
		    'name'    => 'Attachments',
		    'desc'    => 'Upload an image or enter an URL.',
		    'id'      => 'cr_material_attachment',
		    'type'    => 'file',
		    // Optional:
		    'options' => array(
		        'url' => false, // Hide the text input for the url
		    ),
		    'text'    => array(
		        'add_upload_file_text' => 'Add File' // Change upload button text. Default: "Add or Upload File"
		    ),
		) );
	}
	
	
  }
} 

$creport = new TracFlo_Material();
?>